# Generated by Django 3.2 on 2023-08-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='roi',
            field=models.FloatField(default=1e-07, null=True),
        ),
    ]
