# Generated by Django 3.2 on 2023-08-16 02:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0002_alter_client_roi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mimimum_amount', models.FloatField(blank=True, default=0, null=True)),
                ('maximum_amount', models.FloatField(blank=True, default=0, null=True)),
                ('return_of_investment', models.CharField(blank=True, max_length=5000, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_agenda', models.CharField(blank=True, default='Live Video', max_length=68, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message_body', models.CharField(blank=True, max_length=1500, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomura_app.client')),
            ],
        ),
    ]
