# Generated by Django 3.2 on 2023-08-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0003_notification_plan_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_body',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
