# Generated by Django 3.2 on 2023-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0004_alter_notification_message_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='profile_pic',
            new_name='ID_CARD',
        ),
        migrations.AddField(
            model_name='client',
            name='Date_of_birth',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER'), ('RATHER NOT SAY', 'RATHER NOT SAY')], default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='monthly_income',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_age',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_fullname',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER'), ('RATHER NOT SAY', 'RATHER NOT SAY')], default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_home_address',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='next_of_kin_phonenumber',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='reason_for_investing',
            field=models.CharField(blank=True, default='update your account', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='relationship_status_with_next_of_kin',
            field=models.CharField(blank=True, choices=[('FATHER', 'FATHER'), ('MOTHER', 'MOTHER'), ('SIBLING', 'SIBLING'), ('SPOUSE', 'SPOUSE'), ('OTHERS', 'OTHERS')], default='update your account', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='roi',
            field=models.FloatField(default=0.015, null=True),
        ),
    ]
