# Generated by Django 3.2 on 2023-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0006_notification_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(blank=True, max_length=68, null=True)),
                ('percentage_return', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('maximum_amount', models.FloatField(default=0, null=True)),
                ('minimum_amount', models.FloatField(default=0, null=True)),
            ],
        ),
    ]
