# Generated by Django 3.2 on 2024-07-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomura_app', '0007_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=68, null=True)),
                ('client_email', models.CharField(blank=True, max_length=68, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nomura_app.client')),
            ],
        ),
    ]
